nginx:
  image: ivphpan/nginx
  ports:
    - 80:80
  volumes:
    - ./:/www
    - ./docker/site.conf:/etc/nginx/sites-available/default
    - ./docker/nginx.conf:/etc/nginx/nginx.conf
  links:
    - php
  privileged: true
php:
  image: phpxdebugnew
  ports:
    - 9000:9000
  volumes:
    - ./:/www
  links:
    - postgres
    - memcached

memcached:
  image: memcached
  ports:
    - 11211:11211

postgres:
  image: postgres
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=123
  volumes:
    - ~/Containers/ivphpan-postgres/data:/var/lib/postgresql
    - ./:/www

